# Generated by Django 5.0.4 on 2024-05-27 18:53

import ckeditor.fields
import django.db.models.deletion
import page.devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Product Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slogan', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='images/devices/product/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Product Name')),
                ('model', models.CharField(max_length=30, verbose_name='Product Model')),
                ('price', models.CharField(max_length=20)),
                ('short_description', ckeditor.fields.RichTextField(verbose_name='Short Description')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('long_description', ckeditor.fields.RichTextField(verbose_name='Long Description')),
                ('additional_information', ckeditor.fields.RichTextField(blank=True, verbose_name='Additional Information')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.productcategory', verbose_name='Categories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFooterImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank='True', upload_to='images/products/', validators=[page.devices.models.validate_image_size, page.devices.models.validate_image_type], verbose_name='Main Image')),
                ('footer1', models.ImageField(blank='True', upload_to='images/devices/products/', verbose_name='Example 1')),
                ('footer2', models.ImageField(blank='True', upload_to='images/devices/products/', verbose_name='Example 2')),
                ('footer3', models.ImageField(blank='True', upload_to='images/devices/products/', verbose_name='Example 3')),
                ('footer4', models.ImageField(blank='True', upload_to='images/devices/products/', verbose_name='Example 4')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.product', verbose_name='Product')),
            ],
        ),
    ]
