# Generated by Django 5.0.1 on 2024-01-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("img", models.CharField(max_length=70)),
                ("title", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=20)),
                ("discount", models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
