# Generated by Django 5.0.4 on 2024-05-27 19:05

import django.db.models.deletion
import page.devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank='True', upload_to='images/products/', validators=[page.devices.models.validate_image_size, page.devices.models.validate_image_type], verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.product', verbose_name='Product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductFooterImages',
        ),
    ]
