# Generated by Django 5.0.4 on 2024-05-27 19:12

import page.devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_productimages_delete_productfooterimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ('Product',), 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': ('Product Image',), 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank='True', upload_to='images/devices/products/', validators=[page.devices.models.validate_image_size, page.devices.models.validate_image_type], verbose_name='Image'),
        ),
    ]
