# Generated by Django 5.0.2 on 2024-02-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0002_rename_img_product_img_path_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="image/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="img_path",
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
