# Generated by Django 5.0.2 on 2024-02-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0003_alter_product_image_alter_product_img_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
