# Generated by Django 5.0.2 on 2024-02-16 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0004_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="img",
        ),
        migrations.RemoveField(
            model_name="product",
            name="img_path",
        ),
    ]
