# Generated by Django 5.0.2 on 2024-03-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0005_rename_image_product_img_remove_product_img_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.FileField(default=1, upload_to="images/houses/"),
            preserve_default=False,
        ),
    ]
