# Generated by Django 5.0.2 on 2024-03-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0006_product_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
        migrations.AddField(
            model_name="product",
            name="footer_img1",
            field=models.ImageField(blank=True, upload_to="images/products/"),
        ),
        migrations.AddField(
            model_name="product",
            name="footer_img2",
            field=models.ImageField(blank=True, upload_to="images/products/"),
        ),
        migrations.AddField(
            model_name="product",
            name="footer_img3",
            field=models.ImageField(blank=True, upload_to="images/products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(blank=True, upload_to="images/products/"),
        ),
    ]
