# Generated by Django 5.0.2 on 2024-03-04 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0007_remove_product_images_product_footer_img1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="footer_img1",
        ),
        migrations.RemoveField(
            model_name="product",
            name="footer_img2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="footer_img3",
        ),
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(
                blank=True, upload_to="images/products/", verbose_name="Main Image"
            ),
        ),
        migrations.CreateModel(
            name="Product_Images",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                (
                    "footer_img1",
                    models.ImageField(
                        blank=True,
                        upload_to="images/products/",
                        verbose_name="Footer Image 1",
                    ),
                ),
                (
                    "footer_img2",
                    models.ImageField(
                        blank=True,
                        upload_to="images/products/",
                        verbose_name="Footer Image 2",
                    ),
                ),
                (
                    "footer_img3",
                    models.ImageField(
                        blank=True,
                        upload_to="images/products/",
                        verbose_name="Footer Image 3",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.product",
                    ),
                ),
            ],
        ),
    ]
