# Generated by Django 5.0.2 on 2024-03-04 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0008_remove_product_footer_img1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product_images",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="devices.product_images",
                verbose_name="Product Images",
            ),
        ),
    ]
