# Generated by Django 5.0.2 on 2024-03-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0009_remove_product_images_product_product_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
        migrations.AddField(
            model_name="product",
            name="footer_img1",
            field=models.ImageField(
                blank=True, upload_to="images/products/", verbose_name="Footer Image 1"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="footer_img2",
            field=models.ImageField(
                blank=True, upload_to="images/products/", verbose_name="Footer Image 2"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="footer_img3",
            field=models.ImageField(
                blank=True, upload_to="images/products/", verbose_name="Footer Image 3"
            ),
        ),
        migrations.DeleteModel(
            name="Product_Images",
        ),
    ]
