# Generated by Django 5.0.2 on 2024-03-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0010_remove_product_images_product_footer_img1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_Footer_Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank="True",
                        default="",
                        null="True",
                        upload_to="images/products/",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="devices.product",
                    ),
                ),
            ],
        ),
    ]
