# Generated by Django 5.0.2 on 2024-03-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0011_product_footer_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="footer_img1",
        ),
        migrations.RemoveField(
            model_name="product",
            name="footer_img2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="footer_img3",
        ),
        migrations.CreateModel(
            name="ProductFooterImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank="True",
                        upload_to="images/devices/products/",
                        verbose_name="Image 1",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank="True",
                        upload_to="images/devices/products/",
                        verbose_name="Image 2",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank="True",
                        upload_to="images/devices/products/",
                        verbose_name="Image 3",
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank="True",
                        upload_to="images/devices/products/",
                        verbose_name="Image 4",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="devices.product",
                        verbose_name="Product",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Product_Footer_Images",
        ),
    ]
