# Generated by Django 5.0.2 on 2024-03-04 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0012_remove_product_footer_img1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productfooterimages",
            old_name="image1",
            new_name="footer1",
        ),
    ]
