# Generated by Django 5.0.2 on 2024-03-04 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0013_rename_image1_productfooterimages_footer1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productfooterimages",
            old_name="image2",
            new_name="footer2",
        ),
        migrations.RenameField(
            model_name="productfooterimages",
            old_name="image3",
            new_name="footer3",
        ),
        migrations.RenameField(
            model_name="productfooterimages",
            old_name="image4",
            new_name="footer4",
        ),
    ]
