# Generated by Django 5.0.2 on 2024-03-11 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0014_rename_image2_productfooterimages_footer2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="img",
        ),
        migrations.AddField(
            model_name="productfooterimages",
            name="img",
            field=models.ImageField(
                blank="True", upload_to="images/products/", verbose_name="Main Image"
            ),
        ),
        migrations.AlterField(
            model_name="productfooterimages",
            name="footer1",
            field=models.ImageField(
                blank="True",
                upload_to="images/devices/products/",
                verbose_name="Example 1",
            ),
        ),
        migrations.AlterField(
            model_name="productfooterimages",
            name="footer2",
            field=models.ImageField(
                blank="True",
                upload_to="images/devices/products/",
                verbose_name="Example 2",
            ),
        ),
        migrations.AlterField(
            model_name="productfooterimages",
            name="footer3",
            field=models.ImageField(
                blank="True",
                upload_to="images/devices/products/",
                verbose_name="Example 3",
            ),
        ),
        migrations.AlterField(
            model_name="productfooterimages",
            name="footer4",
            field=models.ImageField(
                blank="True",
                null="False",
                upload_to="images/devices/products/",
                verbose_name="Example 4",
            ),
        ),
        migrations.AlterField(
            model_name="productfooterimages",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="devices.product",
                verbose_name="Product",
            ),
        ),
    ]
