# Generated by Django 5.0.4 on 2024-05-07 15:39

import page.devices.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0015_remove_product_img_productfooterimages_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfooterimages",
            name="footer4",
            field=models.ImageField(
                blank="True",
                default=1,
                upload_to="images/devices/products/",
                verbose_name="Example 4",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productfooterimages",
            name="img",
            field=models.ImageField(
                blank="True",
                upload_to="images/products/",
                validators=[
                    page.devices.models.validate_image_size,
                    page.devices.models.validate_image_type,
                ],
                verbose_name="Main Image",
            ),
        ),
    ]
