# Generated by Django 5.0.4 on 2024-05-07 16:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0016_alter_productfooterimages_footer4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
