# Generated by Django 5.0.4 on 2024-05-07 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0017_product_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
