# Generated by Django 5.0.4 on 2024-05-07 20:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0018_remove_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(default=1, verbose_name="Description"),
            preserve_default=False,
        ),
    ]
