# Generated by Django 5.0.2 on 2024-02-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=20)),
                ("number", models.CharField(max_length=20)),
            ],
        ),
    ]
