# Generated by Django 5.0.4 on 2024-05-21 13:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("image", models.ImageField(upload_to="images/blog/")),
            ],
        ),
        migrations.AlterField(
            model_name="categories",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="MainBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(upload_to="images/blog/", verbose_name="Image"),
                ),
                ("publish_date", models.DateField(verbose_name="Publish Date")),
                ("publisher", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=50)),
                (
                    "subtitle",
                    ckeditor.fields.RichTextField(verbose_name="Blog Description"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.categories",
                    ),
                ),
            ],
        ),
    ]
