# Generated by Django 5.0.4 on 2024-05-21 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_advertisement_alter_categories_id_mainblog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainblog",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.categories",
                verbose_name="Category",
            ),
        ),
    ]
