# Generated by Django 5.0.4 on 2024-05-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_mainblog_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainblog",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.categories"
            ),
        ),
    ]
