# Generated by Django 5.0.4 on 2024-05-21 14:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="images/doctors/")),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("profession", models.CharField(max_length=50)),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="Doctor Description"),
                ),
            ],
        ),
    ]
