# Generated by Django 5.0.4 on 2024-05-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("our_doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Page Title")),
                ("header", models.CharField(max_length=50, verbose_name="Header")),
                ("text", models.CharField(max_length=50, verbose_name="Text")),
            ],
        ),
    ]
