# Generated by Django 5.0.1 on 2024-01-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=150)),
                ("toggle", models.CharField(blank=True, max_length=20)),
                ("body", models.TextField()),
            ],
        ),
    ]
