# Generated by Django 5.0.4 on 2024-05-21 17:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0002_alter_questions_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Page Title")),
                (
                    "header",
                    models.CharField(blank=True, max_length=50, verbose_name="Header"),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="Description"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="questions",
            name="toggle",
        ),
        migrations.AlterField(
            model_name="questions",
            name="body",
            field=models.TextField(verbose_name="Body"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="title",
            field=models.CharField(max_length=70, verbose_name="Title"),
        ),
    ]
