# Generated by Django 5.0.1 on 2024-01-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("icon", models.TextField(max_length=70)),
                ("title", models.CharField(max_length=50)),
                ("subtitle", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("icon", models.TextField(max_length=70)),
                ("title", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
