# Generated by Django 5.0.1 on 2024-01-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_us", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("your_name", models.CharField(max_length=50)),
                ("your_phone", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("venue", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=50)),
            ],
        ),
    ]
