# Generated by Django 5.0.1 on 2024-02-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_us", "0002_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="icon",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="card",
            name="subtitle",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="card",
            name="title",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="form",
            name="icon",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="form",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="form",
            name="title",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="form",
            name="type",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
