# Generated by Django 5.0.4 on 2024-05-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_us", "0004_alter_form_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("subtitle", models.CharField(max_length=20)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("address", "Address"),
                            ("mail", "Mail"),
                            ("phone", "Phone"),
                            ("hour", "Hour"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("mail", "Mail"),
                            ("linkedin", "Linkedin"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Card",
        ),
    ]
