# Generated by Django 5.0.4 on 2024-05-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_us", "0005_contactinfo_socialinfo_delete_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40, verbose_name="Page Title")),
                ("header", models.CharField(max_length=40, verbose_name="Header")),
                ("description", models.CharField(max_length=50)),
                (
                    "contact_title",
                    models.CharField(max_length=50, verbose_name="Contact Info Title"),
                ),
                ("address", models.CharField(max_length=40)),
            ],
        ),
    ]
