# Generated by Django 5.0.1 on 2024-01-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("img", models.CharField(max_length=20)),
                ("dateAttr", models.CharField(max_length=30)),
                ("day", models.PositiveIntegerField()),
                ("month", models.CharField(max_length=10)),
                ("year", models.PositiveIntegerField()),
                ("commCount", models.IntegerField()),
                ("publisher", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=50)),
                ("to", models.CharField(max_length=10)),
                ("subtitle", models.TextField()),
                ("single", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Clients",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("img", models.CharField(max_length=50)),
                ("hover", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="IconBox",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("icon", models.CharField(max_length=70, unique=True)),
                ("title", models.CharField(max_length=70, unique=True)),
                ("subtitle", models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceBox",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("icon", models.CharField(max_length=30, unique=True)),
                ("title", models.CharField(max_length=30, unique=True)),
                ("subtitle", models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("img", models.TextField(max_length=100)),
                ("content", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("img", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=30)),
                ("subtitle", models.CharField(max_length=30)),
                ("body", models.TextField()),
            ],
        ),
    ]
