# Generated by Django 5.0.1 on 2024-02-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Header",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=20)),
                ("link", models.CharField(max_length=20)),
            ],
        ),
    ]
