# Generated by Django 5.0.1 on 2024-02-06 19:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="iconbox",
            name="description",
            field=ckeditor.fields.RichTextField(default=1, verbose_name="Description"),
            preserve_default=False,
        ),
    ]
