# Generated by Django 5.0.2 on 2024-02-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_remove_iconbox_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="img1",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
