# Generated by Django 5.0.2 on 2024-02-10 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_testimonial_img1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="img1",
        ),
    ]
