# Generated by Django 5.0.2 on 2024-02-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_remove_testimonial_img1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="img",
            new_name="img_path",
        ),
        migrations.AddField(
            model_name="team",
            name="image",
            field=models.ImageField(default=1, upload_to="views/ui/images"),
            preserve_default=False,
        ),
    ]
