# Generated by Django 5.0.2 on 2024-02-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_rename_img_team_img_path_team_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="src/views/ui/images")),
            ],
        ),
        migrations.RemoveField(
            model_name="team",
            name="image",
        ),
    ]
