# Generated by Django 5.0.2 on 2024-02-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_testmodel_remove_team_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestModel",
        ),
        migrations.RemoveField(
            model_name="team",
            name="img_path",
        ),
        migrations.AddField(
            model_name="team",
            name="img",
            field=models.ImageField(default=1, upload_to="src/views/ui/images"),
            preserve_default=False,
        ),
    ]
