# Generated by Django 5.0.2 on 2024-02-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_delete_testmodel_remove_team_img_path_team_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="img",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
