# Generated by Django 5.0.2 on 2024-02-13 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_team_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="img",
            new_name="img_path",
        ),
        migrations.RenameField(
            model_name="clients",
            old_name="img",
            new_name="img_path",
        ),
        migrations.RenameField(
            model_name="testimonial",
            old_name="img",
            new_name="img_path",
        ),
    ]
