# Generated by Django 5.0.2 on 2024-02-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_rename_img_blog_img_path_rename_img_clients_img_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
