# Generated by Django 5.0.2 on 2024-02-14 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_team_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="img_path",
            new_name="img",
        ),
    ]
