# Generated by Django 5.0.2 on 2024-02-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_rename_img_path_blog_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clients",
            name="img_path",
        ),
        migrations.AddField(
            model_name="clients",
            name="img",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
    ]
