# Generated by Django 5.0.2 on 2024-02-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_remove_testimonial_img_path_testimonial_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="img",
            field=models.ImageField(upload_to="images/blog/"),
        ),
    ]
