# Generated by Django 5.0.4 on 2024-05-21 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_alter_blog_img"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Team",
        ),
    ]
