# Generated by Django 5.0.4 on 2024-05-21 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_delete_team"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="Clients",
        ),
    ]
