# Generated by Django 5.0.4 on 2024-05-21 19:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_delete_blog_delete_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/home/', verbose_name='Image')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('slogan', models.CharField(max_length=30, verbose_name='Slogan')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/home/', verbose_name='Background Image')),
                ('title', models.CharField(max_length=45, verbose_name='Title')),
                ('slogan', models.CharField(max_length=70, verbose_name='Slogan')),
            ],
        ),
    ]
