# Generated by Django 5.0.4 on 2024-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        upload_to="images/about_us/", verbose_name="Brand Image"
                    ),
                ),
                ("link", models.URLField(verbose_name="Brand Link")),
            ],
        ),
    ]
