# Generated by Django 5.0.4 on 2024-05-21 17:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about_us", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="Page Title")),
                (
                    "under_title",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Page Under Title"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/about_us/", verbose_name="Image"
                    ),
                ),
                ("header", models.CharField(max_length=40, verbose_name="Header")),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="Description"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/about_us/", verbose_name="Certificate Image"
                    ),
                ),
            ],
        ),
    ]
